#!/usr/bin/env bash	

mkdir -p ~/bin/{gitapps,c,py,js,rust,go,web}

#add stuff required to install some apps
apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common

#add i386 for steam install
dpkg --add-architecture i386
#add docker repository
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#add ppsspp repostiory
add-apt-repository -y ppa:ppsspp/stable
#add sublime repository
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" > /etc/apt/sources.list.d/sublime-text.list
#add albert repository
sh -c "echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/home:manuelschneid3r.list"
curl https://build.opensuse.org/projects/home:manuelschneid3r/public_key | apt-key add -
add-apt-repository -y multiverse

#install discord
wget -O discord.deb "https://discordapp.com/api/download?platform=linux&format=deb"
dpkg -i ./discord.deb

#install rust
curl https://sh.rustup.rs -sSf | sh

#install a bunch of applications
apt-get install -y kde-plasma-desktop nnn albert conky firefox mednafen ppsspp sublime-text gimp steam mpv gpick nethack-console screenfetch libfftw3-dev libncursesw5-dev cmake docker-ce docker-ce-cli containerd.io

apt-get install -fy
apt-get -y update
apt-get -y upgrade