#!/usr/bin/env bash	

mkdir -p ~/bin/{gitapps,c,python,node}

apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common

dpkg --add-architecture i386
add-apt-repository ppa:noobslab/themes
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
add-apt-repository -y ppa:ppsspp/stable
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" > /etc/apt/sources.list.d/sublime-text.list
sh -c "echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/home:manuelschneid3r.list"
curl https://build.opensuse.org/projects/home:manuelschneid3r/public_key | sudo apt-key add -
add-apt-repository -y multiverse

wget -O discord.deb "https://discordapp.com/api/download?platform=linux&format=deb"

apt-get -y update
apt-get -y upgrade

git clone https://github.com/cmus/cmus.git ~/bin/gitapps/cmus
( cd ~/bin/gitapps/cmus && make && make install )
git clone https://github.com/erikdubois/Super-Ultra-Flat-Numix-Remix.git ~/bin/gitapps/Super-Ultra-Flat-Numix-Remix
mv ~/bin/gitapps/Super-Ultra-Flat-Numix-Remix/surfn-icons/* ~/.icons

apt-get install -y lightdm lxde nnn albert arc-theme firefox mednafen ppsspp sublime-text gimp steam mpv gpick nethack-console screenfetch libfftw3-dev libncursesw5-dev cmake docker-ce docker-ce-cli containerd.io

dpkg -i ./discord.deb
apt-get install -fy