#!/usr/bin/env bash	

dpkg --add-architecture -y i386
add-apt-repository -y ppa:agornostal/ulauncher
add-apt-repository -y ppa:ppsspp/stable
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" > /etc/apt/sources.list.d/sublime-text.list
add-apt-repository -y multiverse

apt-get -y update
apt-get -y upgrade

wget -O discord.deb "https://discordapp.com/api/download?platform=linux&format=deb"
dpkg -i ./discord.deb
sudo apt-get install -fy

apt-get install -y lightdm lxde nnn firefox cmus nestopia ppsspp sublime-text gimp steam-installer mpv gpick nethack-console ulauncher screenfetch

reboot